# Markdown for the application.

CODE_MARKDOWN = """
Welcome to the Llama 2 Finetuning Kit!

This tab is your view of the project and is meant as a reference resource for file paths and navigation. Selecting any file will open it up for you to view as reference.

To edit the code, please use the **JupyterLab** application or an IDE of your choice. 
"""

MODEL_MARKDOWN = """
This tab lets you select a model to finetune. Please use the following GPU Sizing Guide: 

| Model      | Minimum Hardware |
| ---------- | ---------------- |
| Llama2 7B  | 1x A100 80G      |
| Llama2 13B | 1x A100 80G      |
| Llama2 70B | 4x A100 80G      |

Then, download the model weights to the system and convert them to .nemo format for finetuning. Be patient, as this can take several minutes to complete.  

"""

DATA_MARKDOWN = """
This tab lets you select a dataset (in .jsonl) to finetune on. You can either select a preloaded dataset to use, or bring your own dataset. 

To use a preloaded dataset, select the option. Then from the dropdown menu, select a dataset to use. 

**SQuAD**: The Stanford Question Answer Dataset is a general dataset for finetuning a base model for the question-answering task. \n
**PubMedQA**: The PubMedQA Dataset is a medical publication dataset for finetuning a base model on a domain-specific knowledge base.

To bring your own dataset, ensure you have split it into a train, validation, and (optionally) a test set. Then, select the option and begin uploading each dataset to the project. 

One formatted example of a valid dataset entry is as follows, but your own data can vary: 
```json
{
    "input": "QUESTION: Failed IUD insertions in community practice: an under-recognized problem? \n\t\tCONTEXT: The data analysis was conducted to describe the rate of unsuccessful copper T380A intrauterine device (IUD) insertions among women using the IUD for emergency contraception (EC) at community family planning clinics in Utah... \n\t\tTARGET: the answer to the question given the context is (yes|no|maybe): ",
    "output": "yes"
}
```
"""

CONFIG_MARKDOWN = """
This tab lets you tune the configuration parameters for this finetuning job and then start the finetuning. For a full list of parameters and their descriptions, see here (LINK). There are a few notable locations where you need to bring in your own configurations, denoted by the term ``TODO``.

``restore_from_path``: This is the path of the model .nemo checkpoint. Add in your selected model size in parameters, eg. "7b".\n
``train_ds/file_names``: This is the name of the training dataset, eg. "pubmedqa_train.jsonl".\n
``validation_ds/file_names``: This is the name of the validation dataset, eg. "pubmedqa_val.jsonl".\n
``test_ds/file_names``: This is the name of the test dataset, eg. "pubmedqa_test.jsonl".

Be sure to **save** any changes to the configurations before proceeding. 
"""

CONFIG_EVAL_MARKDOWN = """
This tab lets you tune the configuration parameters for model evaluation. For a full list of parameters and their descriptions, see here (LINK). Be sure to save any changes before proceeding. There are a few notable locations where you need to bring in your own configurations, denoted by the term ``TODO``.

``restore_from_path``: This is the path of the model .nemo checkpoint. Add in your selected model size in parameters, eg. "7b".\n
``test_ds/file_names``: This is the name of the test dataset, eg. "pubmedqa_test.jsonl".

Be sure to **save** any changes to the configurations before proceeding. 
"""

FINETUNE_MARKDOWN = """
Select the button to begin finetuning. Use the console output below to monitor progress as this process may take a while to complete. 
"""

EVAL_MARKDOWN = """
Evaluate the responses generated by the fine-tuned model. How well does it do on your fine-tuning task? Or on your specific domain knowledge? 
"""